"""deatails table and relation to users

Revision ID: 595f762766e3
Revises: 8c0ccbb15d1b
Create Date: 2020-11-22 13:28:33.435649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595f762766e3'
down_revision = '8c0ccbb15d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_author', sa.String(length=100), nullable=True),
    sa.Column('sec_author', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publishment_year', sa.String(length=10), nullable=True),
    sa.Column('pages', sa.String(length=10), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_details_main_author'), 'book_details', ['main_author'], unique=False)
    op.create_index(op.f('ix_book_details_pages'), 'book_details', ['pages'], unique=False)
    op.create_index(op.f('ix_book_details_publishment_year'), 'book_details', ['publishment_year'], unique=False)
    op.create_index(op.f('ix_book_details_sec_author'), 'book_details', ['sec_author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_details_sec_author'), table_name='book_details')
    op.drop_index(op.f('ix_book_details_publishment_year'), table_name='book_details')
    op.drop_index(op.f('ix_book_details_pages'), table_name='book_details')
    op.drop_index(op.f('ix_book_details_main_author'), table_name='book_details')
    op.drop_table('book_details')
    # ### end Alembic commands ###
