"""book table

Revision ID: 8c0ccbb15d1b
Revises: 
Create Date: 2020-11-22 13:12:28.815042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0ccbb15d1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('publishment_house', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_bookname'), 'book', ['bookname'], unique=True)
    op.create_index(op.f('ix_book_publishment_house'), 'book', ['publishment_house'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_publishment_house'), table_name='book')
    op.drop_index(op.f('ix_book_bookname'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
